/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import config.interfaceVET;
import dao.impl.LoginImpl;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Login;

/**
 *
 * @author Miguel Casa
 */
public class Loginfrm extends javax.swing.JFrame {
    String usu = "";
    /**
     * Creates new form Loginfrm
     */
    public Loginfrm() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/salud.png")));
        initComponents();
        this.redimensionarIMG();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        logoLog = new javax.swing.JLabel();
        iconLog = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtcontra = new javax.swing.JPasswordField();
        inicioLog = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnlog = new javax.swing.JPanel();
        btnLogin = new javax.swing.JLabel();
        btnexit = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesión");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("[NOMBRE CLINICA]");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        logoLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoLog.png"))); // NOI18N
        jPanel2.add(logoLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 200, 180));

        iconLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoLog.jpg"))); // NOI18N
        jPanel2.add(iconLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 520));

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        jLabel7.setText("USUARIO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        txtusuario.setFont(new java.awt.Font("Microsoft Tai Le", 0, 16)); // NOI18N
        txtusuario.setBorder(null);
        jPanel2.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 430, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setAutoscrolls(true);
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 430, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        jLabel1.setText("CONTRASEÑA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setAutoscrolls(true);
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 430, -1));

        txtcontra.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtcontra.setBorder(null);
        jPanel2.add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 430, 30));

        inicioLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estrella.png"))); // NOI18N
        jPanel2.add(inicioLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 40, 40));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 30)); // NOI18N
        jLabel3.setText("BIENVENIDO USUARIO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel4.setText("INICIAR SESION");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        btnlog.setBackground(new java.awt.Color(153, 204, 255));
        btnlog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin.setText("SIGUIENTE");
        btnLogin.setToolTipText("");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnlog.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        jPanel2.add(btnlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 130, 40));

        btnexit.setBackground(new java.awt.Color(255, 51, 51));
        btnexit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("X");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnexit.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel2.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
        btnexit.setBackground(new Color(153,0,51));
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
        btnexit.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        this.validar();
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnlog.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnlog.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_btnLoginMouseExited
    //VARIABLES GENERALES 
    private Login logueo = new Login(); // declarando mi objeto LOGIN
    
    private interfaceVET loginIntf  = new LoginImpl(); // declarar interface
    
    public void validar(){
        usu = txtusuario.getText();
        String contraseña = String.valueOf(txtcontra.getPassword());

        if(!"".equals(usu)   &&  !"".equals(contraseña) ){
            logueo =    loginIntf.obtenerLogin(usu, contraseña);
            if(logueo!=null){
                       Principal principal = new Principal();
                       principal.setVariable(usu);
                       principal.setVisible(true);
                       dispose();
            }else {
                        JOptionPane.showMessageDialog(this, "Usuario no encontrado", "ERROR",JOptionPane.ERROR_MESSAGE);
                    }
        }else{
            JOptionPane.showMessageDialog(this, "Complete ambos campos", "Datos faltantes",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    public void redimensionarIMG(){
        
        Icon iconPred = iconLog.getIcon();
        Image imgPred = ((ImageIcon) iconPred).getImage();
        Image imgIcon = imgPred.getScaledInstance(iconLog.getWidth(), iconLog.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoRedimensionado = new ImageIcon(imgIcon);
        iconLog.setIcon(iconoRedimensionado);
        
        Icon iconPred2 = logoLog.getIcon();
        Image imgPred2 = ((ImageIcon) iconPred2).getImage();
        Image imgIcon2 = imgPred2.getScaledInstance(logoLog.getWidth(), logoLog.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoRedimensionado2 = new ImageIcon(imgIcon2);
        logoLog.setIcon(iconoRedimensionado2);
        
        Icon iconPred3 = inicioLog.getIcon();
        Image imgPred3 = ((ImageIcon) iconPred3).getImage();
        Image imgIcon3 = imgPred3.getScaledInstance(inicioLog.getWidth(), inicioLog.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoRedimensionado3 = new ImageIcon(imgIcon3);
        inicioLog.setIcon(iconoRedimensionado3);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.setProperty("awt.useSystemAAFontSettings", "lcd"); // use font antialiasing
        System.setProperty("swing.aatext", "true");
        //txtusuario.setFocusable(false);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginfrm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JPanel btnexit;
    private javax.swing.JPanel btnlog;
    private javax.swing.JLabel iconLog;
    private javax.swing.JLabel inicioLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logoLog;
    private javax.swing.JPasswordField txtcontra;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
